### ISSUE TITLE
脚本文件

### ISSUE THREAD

**Issue by jouvychen** [jackytallow/houseplus-#8]
请问可以提供数据库脚本文件吗？2774721329@qq.com，先谢谢您了

**Comment by jackytallow** [comment]
目前才看到，数据库文件已经不在了，可以根据项目自己写些测试数据

**Comment by jouvychen** [comment]
好吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jackytallow/houseplus-"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 晚上7:35
收件人:&nbsp;"jackytallow/houseplus-"<houseplus-@noreply.github.com&gt;;
抄送:&nbsp;"陈建伟"<2774721329@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jackytallow/houseplus-] 脚本文件 (#8)





 
目前才看到，数据库文件已经不在了，可以根据项目自己写些测试数据
